# Generated by Django 5.0.4 on 2024-04-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_remove_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
    ]
